package views;
import controllers.KhoanThuManagerPanelController;
import javax.swing.JFrame;

public class KhoanThuPanel extends javax.swing.JPanel {
    
    private JFrame parentFrame;
    KhoanThuManagerPanelController controller;

    public KhoanThuPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        controller = new KhoanThuManagerPanelController(parentFrame,mainJpn);
        controller.SetView("KhoanTien");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        mainJpn = new javax.swing.JPanel();
        khoanTienBtn = new javax.swing.JButton();
        thuTienBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        button1.setLabel("button1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(851, 465));

        javax.swing.GroupLayout mainJpnLayout = new javax.swing.GroupLayout(mainJpn);
        mainJpn.setLayout(mainJpnLayout);
        mainJpnLayout.setHorizontalGroup(
            mainJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainJpnLayout.setVerticalGroup(
            mainJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        khoanTienBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        khoanTienBtn.setText("Danh Sách Khoản Tiền");
        khoanTienBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khoanTienBtnActionPerformed(evt);
            }
        });

        thuTienBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        thuTienBtn.setText("Danh Sách Thu Tiền");
        thuTienBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuTienBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(khoanTienBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thuTienBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
            .addComponent(mainJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoanTienBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thuTienBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void khoanTienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khoanTienBtnActionPerformed
        // TODO add your handling code here:
        controller.SetView("KhoanTien");
    }//GEN-LAST:event_khoanTienBtnActionPerformed

    private void thuTienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuTienBtnActionPerformed
        // TODO add your handling code here:
        controller.SetView("ThuTien");
    }//GEN-LAST:event_thuTienBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton khoanTienBtn;
    private javax.swing.JPanel mainJpn;
    private javax.swing.JButton thuTienBtn;
    // End of variables declaration//GEN-END:variables
}

