
package views;

import Bean.DanhMucBean;
import controllers.MainController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        setTitle("QUẢN LÝ NHÂN KHẨU");
        List<DanhMucBean> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMucBean("TrangChu", trangChuBtn));
        listDanhMuc.add(new DanhMucBean("NhanKhau", nhanKhauBtn));
        listDanhMuc.add(new DanhMucBean("HoKhau", hoKhauBtn));
        listDanhMuc.add(new DanhMucBean("KhoanThu",khoanThuBtn));
        listDanhMuc.add(new DanhMucBean("NopTien",nopTienBtn));
        
        MainController controller = new MainController(infoPanel, this);
        controller.setEvent(listDanhMuc);
        controller.setView(trangChuBtn, "TrangChu");
        
        // confirm de thuc hien dong
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có đồng ý tắt cửa sổ??", "Xác nhận", JOptionPane.YES_NO_OPTION) == 0) {
                    dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        slidepane = new javax.swing.JPanel();
        trangChuBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nhanKhauBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hoKhauBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        khoanThuBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nopTienBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        headerText = new javax.swing.JLabel();
        headerSep = new javax.swing.JSeparator();
        infoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(155, 155));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slidepane.setBackground(new java.awt.Color(54, 33, 99));
        slidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trangChuBtn.setBackground(new java.awt.Color(85, 65, 118));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trangchu.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("     Trang Chủ");

        javax.swing.GroupLayout trangChuBtnLayout = new javax.swing.GroupLayout(trangChuBtn);
        trangChuBtn.setLayout(trangChuBtnLayout);
        trangChuBtnLayout.setHorizontalGroup(
            trangChuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChuBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        trangChuBtnLayout.setVerticalGroup(
            trangChuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trangChuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(trangChuBtnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        slidepane.add(trangChuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 50));

        nhanKhauBtn.setBackground(new java.awt.Color(85, 65, 118));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nhankhau.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("     Nhân Khẩu");

        javax.swing.GroupLayout nhanKhauBtnLayout = new javax.swing.GroupLayout(nhanKhauBtn);
        nhanKhauBtn.setLayout(nhanKhauBtnLayout);
        nhanKhauBtnLayout.setHorizontalGroup(
            nhanKhauBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanKhauBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        nhanKhauBtnLayout.setVerticalGroup(
            nhanKhauBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanKhauBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhanKhauBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nhanKhauBtnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        slidepane.add(nhanKhauBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 50));

        hoKhauBtn.setBackground(new java.awt.Color(85, 65, 118));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hokhau.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("     Hộ Khẩu");

        javax.swing.GroupLayout hoKhauBtnLayout = new javax.swing.GroupLayout(hoKhauBtn);
        hoKhauBtn.setLayout(hoKhauBtnLayout);
        hoKhauBtnLayout.setHorizontalGroup(
            hoKhauBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoKhauBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        hoKhauBtnLayout.setVerticalGroup(
            hoKhauBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoKhauBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoKhauBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hoKhauBtnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        slidepane.add(hoKhauBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 50));

        khoanThuBtn.setBackground(new java.awt.Color(85, 65, 118));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/khoanthu.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("     Khoản Thu");

        javax.swing.GroupLayout khoanThuBtnLayout = new javax.swing.GroupLayout(khoanThuBtn);
        khoanThuBtn.setLayout(khoanThuBtnLayout);
        khoanThuBtnLayout.setHorizontalGroup(
            khoanThuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoanThuBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        khoanThuBtnLayout.setVerticalGroup(
            khoanThuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoanThuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khoanThuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(khoanThuBtnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        slidepane.add(khoanThuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 50));

        nopTienBtn.setBackground(new java.awt.Color(85, 65, 118));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/noptien.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("     Nộp Tiền");

        javax.swing.GroupLayout nopTienBtnLayout = new javax.swing.GroupLayout(nopTienBtn);
        nopTienBtn.setLayout(nopTienBtnLayout);
        nopTienBtnLayout.setHorizontalGroup(
            nopTienBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nopTienBtnLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        nopTienBtnLayout.setVerticalGroup(
            nopTienBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nopTienBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nopTienBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nopTienBtnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        slidepane.add(nopTienBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 280, 50));

        headerText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        headerText.setForeground(new java.awt.Color(204, 204, 204));
        headerText.setText("Quản Lý ");
        slidepane.add(headerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        headerSep.setBackground(new java.awt.Color(255, 255, 255));
        slidepane.add(headerSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 20));

        bg.add(slidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 850, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator headerSep;
    private javax.swing.JLabel headerText;
    private javax.swing.JPanel hoKhauBtn;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel khoanThuBtn;
    private javax.swing.JPanel nhanKhauBtn;
    private javax.swing.JPanel nopTienBtn;
    private javax.swing.JPanel slidepane;
    private javax.swing.JPanel trangChuBtn;
    // End of variables declaration//GEN-END:variables
}
