package views.NhanKhauManagerFrame;

import Bean.NhanKhauBean;
import controllers.NhanKhauManagerController.ThemNhanKhauController;
import controllers.NhanKhauManagerPanelController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ThemNhanKhauFrame extends javax.swing.JFrame {

    private NhanKhauManagerPanelController parentController;
    private JFrame parentFrame;
    private NhanKhauBean nhanKhauBean;
    private ThemNhanKhauController controller;

    public ThemNhanKhauFrame(NhanKhauManagerPanelController parentController, JFrame parentJFrame) {
        this.parentController = parentController;
        this.nhanKhauBean = new NhanKhauBean();
        this.controller = new ThemNhanKhauController();
        this.parentFrame = parentJFrame;
        this.parentFrame.setEnabled(false);
        initComponents();
        InitAction();
        setTitle("Thêm mới nhân khẩu");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    public void InitAction() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }

        });
    }

    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ngaySinhChooser = new com.raven.datechooser.DateChooser();
        ngayCapCCCDChooser = new com.raven.datechooser.DateChooser();
        ngayChuyenDenChooser = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        txtHoTen = new component.TextField();
        txtQuocTich = new component.TextField();
        txtQueQuan = new component.TextField();
        txtNoiThuongTru = new component.TextField();
        txtBiDanh = new component.TextField();
        txtTonGiao = new component.TextField();
        txtNgheNghiep = new component.TextField();
        txtDanToc = new component.TextField();
        txtNoiCapCCCD = new component.TextField();
        txtNoiLamViec = new component.TextField();
        txtSoCCCD = new component.TextField();
        ccbGioiTinh = new component.Combobox();
        jLabel1 = new javax.swing.JLabel();
        textNgaySinh = new component.TextField();
        txtNgayCapCCCD = new component.TextField();
        textNgayChuyenDen = new component.TextField();
        btnThem = new component.MyButton();

        ngaySinhChooser.setForeground(new java.awt.Color(204, 204, 204));
        ngaySinhChooser.setTextRefernce(textNgaySinh);

        ngayCapCCCDChooser.setForeground(new java.awt.Color(204, 204, 204));
        ngayCapCCCDChooser.setTextRefernce(txtNgayCapCCCD);

        ngayChuyenDenChooser.setForeground(new java.awt.Color(204, 204, 204));
        ngayChuyenDenChooser.setTextRefernce(textNgayChuyenDen);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtHoTen.setBackground(new java.awt.Color(255, 255, 255));
        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtHoTen.setLabelText("Họ tên");

        txtQuocTich.setBackground(new java.awt.Color(255, 255, 255));
        txtQuocTich.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtQuocTich.setLabelText("Quốc tịch");

        txtQueQuan.setBackground(new java.awt.Color(255, 255, 255));
        txtQueQuan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtQueQuan.setLabelText("Quê quán");

        txtNoiThuongTru.setBackground(new java.awt.Color(255, 255, 255));
        txtNoiThuongTru.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNoiThuongTru.setLabelText("Nơi thường trú");

        txtBiDanh.setBackground(new java.awt.Color(255, 255, 255));
        txtBiDanh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtBiDanh.setLabelText("Bí danh");

        txtTonGiao.setBackground(new java.awt.Color(255, 255, 255));
        txtTonGiao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTonGiao.setLabelText("Tôn giáo");

        txtNgheNghiep.setBackground(new java.awt.Color(255, 255, 255));
        txtNgheNghiep.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNgheNghiep.setLabelText("Nghề nghiệp");

        txtDanToc.setBackground(new java.awt.Color(255, 255, 255));
        txtDanToc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDanToc.setLabelText("Dân tộc");

        txtNoiCapCCCD.setBackground(new java.awt.Color(255, 255, 255));
        txtNoiCapCCCD.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNoiCapCCCD.setLabelText("Nơi cấp căn cước");

        txtNoiLamViec.setBackground(new java.awt.Color(255, 255, 255));
        txtNoiLamViec.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNoiLamViec.setLabelText("Nơi làm việc");

        txtSoCCCD.setBackground(new java.awt.Color(255, 255, 255));
        txtSoCCCD.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtSoCCCD.setLabelText("Số căn cước công dân");

        ccbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "                                  ", "Nam", "Nữ" }));
        ccbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ccbGioiTinh.setLabeText("Giới tính");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Thêm Nhân Khẩu");

        textNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        textNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textNgaySinh.setLabelText("Ngày Sinh");

        txtNgayCapCCCD.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayCapCCCD.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNgayCapCCCD.setLabelText("Ngày cấp căn cước");

        textNgayChuyenDen.setBackground(new java.awt.Color(255, 255, 255));
        textNgayChuyenDen.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textNgayChuyenDen.setLabelText("Ngày chuyển đến");

        btnThem.setForeground(new java.awt.Color(51, 51, 51));
        btnThem.setText("Thêm ngay");
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setRadius(5);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(textNgayChuyenDen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBiDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtQueQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNoiThuongTru, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQuocTich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNgayCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(txtNoiCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ccbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(txtSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiThuongTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBiDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNgayChuyenDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(!this.controller.ValidateValue(this, textNgayChuyenDen.getText())) return;
        if(!this.controller.ValidateValue(this, textNgaySinh.getText())) return;
        if(!this.controller.ValidateValue(this, txtBiDanh.getText())) return;
        if(!this.controller.ValidateValue(this, txtDanToc.getText())) return;
        if(!this.controller.ValidateValue(this, txtHoTen.getText())) return;
        if(!this.controller.ValidateValue(this, txtNgayCapCCCD.getText())) return;
        if(!this.controller.ValidateValue(this, txtNgheNghiep.getText())) return;
        if(!this.controller.ValidateValue(this, txtNoiCapCCCD.getText())) return;
        if(!this.controller.ValidateValue(this, txtNoiLamViec.getText())) return;
        if(!this.controller.ValidateValue(this, txtNoiThuongTru.getText())) return;
        if(!this.controller.ValidateValue(this, txtQueQuan.getText())) return;
        if(!this.controller.ValidateValue(this, txtQuocTich.getText())) return;
        if(!this.controller.ValidateValue(this, txtSoCCCD.getText())) return;
        if(!this.controller.ValidateValue(this, txtTonGiao.getText())) return;
        if(!this.controller.ValidateValueForCCCD(this, txtSoCCCD.getText())) return;
        try{
            this.controller.ThemMoiNhanKhau(txtSoCCCD.getText(), txtHoTen.getText(), textNgaySinh.getDate(),
                    ccbGioiTinh.getSelectedItem().toString(), txtQuocTich.getText(), txtQueQuan.getText(),
                    txtNoiThuongTru.getText(), txtNgayCapCCCD.getDate(), txtNoiCapCCCD.getText(),
                    txtBiDanh.getText(), txtDanToc.getText(), txtTonGiao.getText(),
                    txtNgheNghiep.getText(), txtNoiLamViec.getText(), textNgayChuyenDen.getDate());
            JOptionPane.showMessageDialog(null, "Thêm thành công!!");
            close();
            parentController.Refresh();
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btnThem;
    private component.Combobox ccbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.raven.datechooser.DateChooser ngayCapCCCDChooser;
    private com.raven.datechooser.DateChooser ngayChuyenDenChooser;
    private com.raven.datechooser.DateChooser ngaySinhChooser;
    private component.TextField textNgayChuyenDen;
    private component.TextField textNgaySinh;
    private component.TextField txtBiDanh;
    private component.TextField txtDanToc;
    private component.TextField txtHoTen;
    private component.TextField txtNgayCapCCCD;
    private component.TextField txtNgheNghiep;
    private component.TextField txtNoiCapCCCD;
    private component.TextField txtNoiLamViec;
    private component.TextField txtNoiThuongTru;
    private component.TextField txtQueQuan;
    private component.TextField txtQuocTich;
    private component.TextField txtSoCCCD;
    private component.TextField txtTonGiao;
    // End of variables declaration//GEN-END:variables
}
